/*
 * XML fontconfig document generation.
 */
'use strict';

const { REPLACED } = require('./learning.js');

const escapeXml = value => String(value)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/*
 * The document, and why the Arabic rule is at the bottom of it.
 *
 * fontconfig applies every match in the order it reads them, and `mode=assign`
 * replaces the FIRST family in the pattern while `mode=prepend` puts one in
 * front of it. So a rule that prepends the Arabic family and is then followed
 * by a rule that assigns the Latin one has been undone: the assignment lands on
 * the family the prepend just added. The renames come first and the language
 * rule comes last, and that order is the rule, not a matter of taste.
 *
 * The generic at the foot lists both families in turn. Chromium asks fontconfig
 * for sans-serif and takes what it is given, then looks down the sorted list
 * for a glyph the first family has not got -- which is exactly what an Arabic
 * word in a page that named nothing but sans-serif needs.
 */
const document_ = (resolved, extra = []) => {
  const latin = resolved && resolved.latin && resolved.latin.family;
  if (!latin) return '';
  const arabic = resolved.arabic && resolved.arabic.family &&
    resolved.arabic.family.toLowerCase() !== latin.toLowerCase()
    ? resolved.arabic.family : '';

  const target = escapeXml(latin);
  /* Never a family that was CHOSEN. Both of these lists are families the page
     might name, and one of them can perfectly well be the font the owner
     picked for the other script -- DejaVu Sans is on this machine's Arabic list
     and in REPLACED both. Renaming it would answer every request for the
     Arabic font with the Latin one, including the preview in the settings
     window that is meant to show what was picked. */
  const chosen = [latin, arabic].filter(Boolean).map(name => name.toLowerCase());
  const rules = [...REPLACED, ...extra]
    .filter(name => !chosen.includes(name.toLowerCase()))
    .map(name => `  <match target="pattern">
    <test name="family"><string>${escapeXml(name)}</string></test>
    <edit name="family" mode="assign" binding="strong"><string>${target}</string></edit>
  </match>`)
    .join('\n');

  const byLanguage = arabic ? `
  <!-- Arabic text asks for Arabic glyphs, and this is the only place the two
       scripts can be told apart before a family is chosen. Last, so that the
       renames above cannot assign over it. -->
  <match target="pattern">
    <test name="lang" compare="contains"><string>ar</string></test>
    <edit name="family" mode="prepend" binding="strong"><string>${escapeXml(arabic)}</string></edit>
  </match>
` : '';

  const preferred = [target, ...(arabic ? [escapeXml(arabic)] : [])]
    .map(name => `      <family>${name}</family>`).join('\n');

  return `<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- Generated by whatsapp-desktop. Do not edit: it is rewritten on every start
     from the fonts chosen in Settings, or from the desktop's own. -->
<fontconfig>
  <include ignore_missing="yes">/etc/fonts/fonts.conf</include>

${rules}
${byLanguage}
  <!-- and the generic the page falls through to when it names nothing else -->
  <alias binding="strong">
    <family>sans-serif</family>
    <prefer>
${preferred}
    </prefer>
  </alias>
</fontconfig>
`;
};

module.exports = {
  document_,
  escapeXml,
};
