/*
 * Curated Themes and Hyprland / System Color Adoption.
 *
 * Themes:
 *   - system (Follows OS light/dark)
 *   - dark (WhatsApp standard #111b21)
 *   - light (WhatsApp standard #f0f2f5)
 *   - oled (Pure Pitch-Black #000000 with high contrast for AMOLED screens)
 *   - nord (Arctic Nord palette #2e3440, #88c0d0)
 *   - catppuccin (Catppuccin Mocha #1e1e2e, #89b4fa)
 *
 * Hyprland / Pywal Color Detection:
 *   Detects dynamic colors generated by Pywal, Wallust, or Matugen
 *   (e.g., ~/.cache/wal/colors.json or ~/.config/hypr/colors.conf)
 *   and applies them to the client's accent highlights and sidebar.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');

const THEMES = {
  dark: {
    name: 'Dark',
    bg: '#111b21',
    card: '#202c33',
    border: '#2a3942',
    text: '#e9edef',
    textMuted: '#8696a0',
    accent: '#00a884',
    incomingBubble: '#202c33',
    outgoingBubble: '#005c4b',
  },
  light: {
    name: 'Light',
    bg: '#f0f2f5',
    card: '#ffffff',
    border: '#d1d7db',
    text: '#111b21',
    textMuted: '#667781',
    accent: '#00a884',
    incomingBubble: '#ffffff',
    outgoingBubble: '#d9fdd3',
  },
  oled: {
    name: 'OLED Black',
    bg: '#000000',
    card: '#0c0c0c',
    border: '#1f1f1f',
    text: '#f5f5f5',
    textMuted: '#9e9e9e',
    accent: '#00a884',
    incomingBubble: '#121212',
    outgoingBubble: '#003e33',
  },
  nord: {
    name: 'Nord',
    bg: '#2e3440',
    card: '#3b4252',
    border: '#4c566a',
    text: '#eceff4',
    textMuted: '#d8dee9',
    accent: '#88c0d0',
    incomingBubble: '#3b4252',
    outgoingBubble: '#434c5e',
  },
  catppuccin: {
    name: 'Catppuccin',
    bg: '#1e1e2e',
    card: '#181825',
    border: '#313244',
    text: '#cdd6f4',
    textMuted: '#a6adc8',
    accent: '#89b4fa',
    incomingBubble: '#313244',
    outgoingBubble: '#45475a',
  },
};

/**
 * Detect dynamic system colors from Hyprland/Pywal environment.
 */
function detectHyprlandColors() {
  const home = os.homedir();

  // 1. Check pywal / wallust colors.json
  const walPath = path.join(home, '.cache', 'wal', 'colors.json');
  try {
    if (fs.existsSync(walPath)) {
      const data = JSON.parse(fs.readFileSync(walPath, 'utf8'));
      if (data && data.colors && data.colors.color1) {
        return {
          source: 'pywal',
          accent: data.colors.color4 || data.colors.color1,
          bg: (data.special && data.special.background) || data.colors.color0,
          text: (data.special && data.special.foreground) || data.colors.color7,
          palette: Object.values(data.colors).slice(0, 8),
        };
      }
    }
  } catch (e) {}

  // 2. Check Hyprland colors.conf
  const hyprColors = path.join(home, '.config', 'hypr', 'colors.conf');
  try {
    if (fs.existsSync(hyprColors)) {
      const text = fs.readFileSync(hyprColors, 'utf8');
      const accentMatch = text.match(/\$(?:accent|primary|color4)\s*=\s*(?:rgba?\()?([0-9a-fA-F]{6,8})/);
      if (accentMatch) {
        const hex = '#' + accentMatch[1].slice(0, 6);
        return {
          source: 'hyprland-conf',
          accent: hex,
        };
      }
    }
  } catch (e) {}

  return null;
}

/**
 * Generate CSS overrides for WhatsApp Web page when a custom theme is active.
 */
function getWebThemeCss(themeKey, hyprAccent = null) {
  const theme = THEMES[themeKey];
  if (!theme || themeKey === 'system' || themeKey === 'light' || themeKey === 'dark') {
    if (hyprAccent) {
      return `
        /* Dynamic Hyprland accent tint */
        :root { --accent: ${hyprAccent} !important; --teal: ${hyprAccent} !important; }
        .active-pill { background-color: ${hyprAccent} !important; }
      `;
    }
    return '';
  }

  const effectiveAccent = hyprAccent || theme.accent;

  return `
  /* WhatsApp Desktop - Theme: ${theme.name} */
  :root {
    --bg-color: ${theme.bg} !important;
    --background-default: ${theme.bg} !important;
    --background-default-hover: ${theme.card} !important;
    --panel-background-lighter: ${theme.card} !important;
    --panel-background-deep: ${theme.bg} !important;
    --conversation-panel-background: ${theme.bg} !important;
    --border-strong: ${theme.border} !important;
    --border-subtle: ${theme.border} !important;
    --primary-strong: ${effectiveAccent} !important;
    --primary: ${effectiveAccent} !important;
    --teal: ${effectiveAccent} !important;
  }

  body, #app, #main, #pane-side, [data-testid="conversation-panel-wrapper"] {
    background-color: ${theme.bg} !important;
    color: ${theme.text} !important;
  }

  header, [data-testid="chatlist-header"], [data-testid="conversation-header"] {
    background-color: ${theme.card} !important;
    border-color: ${theme.border} !important;
  }

  .message-in .copyable-text {
    background-color: ${theme.incomingBubble} !important;
    color: ${theme.text} !important;
  }

  .message-out .copyable-text {
    background-color: ${theme.outgoingBubble} !important;
    color: ${theme.text} !important;
  }
  `;
}

module.exports = {
  THEMES,
  detectHyprlandColors,
  getWebThemeCss,
};
